# Generated by Django 3.0.6 on 2020-05-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='nick_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
